devices([
  "iPhone 17 Pro Max",    # 6.9" display
  "iPad Pro 13-inch (M5)" # 13" iPad display
])

languages(["de-DE"])

scheme("AppUITests")
workspace("./ios/App/App.xcworkspace")

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
